
GET http://localhost:3000/catagory
Accept: application/json

###

GET http://localhost:3000/catagory/67795a7e53efe421db2ed1ca
Accept: application/json

###

POST http://localhost:3000/catagory/add
Content-Type: application/json

{
    "name": "Apple",
    "parent": "677d7c90e1223ca141a3fd2f"
}

###

PUT http://localhost:3000/catagory/update/677d7c90e1223ca141a3fd2f
Content-Type: application/json

{
    "name": "cmp"
}

###

DELETE http://localhost:3000/catagory/deleteAll