GET http://localhost:3000/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdlNjE4MWQzYjI3ZmNjZmU3NTBiZjIiLCJ1c2VybmFtZSI6ImthdGV5b2hhbm5lcyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM2MzM4NjczfQ.Q3Tdv7H4MnyykG19kfdktEKFuGchsTtLKZZF04DI8xQ

###

GET http://localhost:3000/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdlNjE4MWQzYjI3ZmNjZmU3NTBiZjIiLCJ1c2VybmFtZSI6ImthdGV5b2hhbm5lcyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM2MzM4NjczfQ.Q3Tdv7H4MnyykG19kfdktEKFuGchsTtLKZZF04DI8xQ

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "kateyohannes",
    "password": "1234567"
}

###

GET http://localhost:3000/user
Accept: application/json

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "1234567"
}


###
DELETE http://localhost:3000/user/delete/677e6151e1aa718e38cab92e